In [27]:
import numpy as np
import pandas as pd

In [28]:
b = pd.read_csv('/content/transaction_data.csv',encoding='latin-1')
b.head()

,Transaction ID,Sender Account ID,Receiver Account ID,Transaction Amount,Transaction Type,Timestamp,Transaction Status,Fraud Flag,Geolocation (Latitude/Longitude),Device Used,Network Slice ID,Latency (ms),Slice Bandwidth (Mbps),PIN Code
0,TXN9520068950,ACC14994,ACC16656,495.90,Deposit,2025-01-17 10:14:00,Failed,True,"34.0522 N, -74.006 W",Desktop,Slice3,10,179,3075
1,TXN9412011085,ACC58958,ACC32826,529.62,Withdrawal,2025-01-17 10:51:00,Success,False,"35.6895 N, -118.2437 W",Mobile,Slice2,11,89,2369
2,TXN4407425052,ACC56321,ACC92481,862.47,Withdrawal,2025-01-17 10:50:00,Failed,False,"48.8566 N, 2.3522 W",Mobile,Slice1,4,53,8039
3,TXN2214150284,ACC48650,ACC76457,1129.88,Transfer,2025-01-17 10:56:00,Success,True,"34.0522 N, -74.006 W",Mobile,Slice3,10,127,6374
4,TXN4247571145,ACC60921,ACC11419,933.24,Deposit,2025-01-17 10:25:00,Success,True,"55.7558 N, 37.6173 W",Mobile,Slice3,20,191,8375

In [29]:
# Step 1: Renaming the columns
a={'Transaction ID':'Transac_id'}
b.rename(columns=a,inplace=True)
b

,Transac_id,Sender Account ID,Receiver Account ID,Transaction Amount,Transaction Type,Timestamp,Transaction Status,Fraud Flag,Geolocation (Latitude/Longitude),Device Used,Network Slice ID,Latency (ms),Slice Bandwidth (Mbps),PIN Code
0,TXN9520068950,ACC14994,ACC16656,495.90,Deposit,2025-01-17 10:14:00,Failed,True,"34.0522 N, -74.006 W",Desktop,Slice3,10,179,3075
1,TXN9412011085,ACC58958,ACC32826,529.62,Withdrawal,2025-01-17 10:51:00,Success,False,"35.6895 N, -118.2437 W",Mobile,Slice2,11,89,2369
2,TXN4407425052,ACC56321,ACC92481,862.47,Withdrawal,2025-01-17 10:50:00,Failed,False,"48.8566 N, 2.3522 W",Mobile,Slice1,4,53,8039
3,TXN2214150284,ACC48650,ACC76457,1129.88,Transfer,2025-01-17 10:56:00,Success,True,"34.0522 N, -74.006 W",Mobile,Slice3,10,127,6374
4,TXN4247571145,ACC60921,ACC11419,933.24,Deposit,2025-01-17 10:25:00,Success,True,"55.7558 N, 37.6173 W",Mobile,Slice3,20,191,8375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,TXN7395336359,ACC79886,ACC14903,1340.76,Transfer,2025-01-17 10:49:00,Success,False,"35.6895 N, -118.2437 W",Mobile,Slice2,19,224,9766
996,TXN2215717837,ACC95972,ACC50750,483.36,Withdrawal,2025-01-17 11:00:00,Failed,True,"55.7558 N, 37.6173 W",Mobile,Slice2,12,56,1009
997,TXN1676848215,ACC95938,ACC18507,199.81,Withdrawal,2025-01-17 10:54:00,Success,False,"34.0522 N, 139.6917 W",Desktop,Slice1,14,151,9301
998,TXN2479413280,ACC76523,ACC95234,1341.86,Transfer,2025-01-17 10:59:00,Success,True,"51.5074 N, 139.6917 W",Mobile,Slice3,8,95,4038
999,TXN3992032184,ACC16789,ACC21980,495.36,Transfer,2025-01-17 10:02:00,Failed,False,"55.7558 N, -74.006 W",Mobile,Slice2,5,155,9888

In [30]:
# STEP 2 : REMOVING DUPLICATE VALUES
b.drop_duplicates(inplace=True)
b

,Transac_id,Sender Account ID,Receiver Account ID,Transaction Amount,Transaction Type,Timestamp,Transaction Status,Fraud Flag,Geolocation (Latitude/Longitude),Device Used,Network Slice ID,Latency (ms),Slice Bandwidth (Mbps),PIN Code
0,TXN9520068950,ACC14994,ACC16656,495.90,Deposit,2025-01-17 10:14:00,Failed,True,"34.0522 N, -74.006 W",Desktop,Slice3,10,179,3075
1,TXN9412011085,ACC58958,ACC32826,529.62,Withdrawal,2025-01-17 10:51:00,Success,False,"35.6895 N, -118.2437 W",Mobile,Slice2,11,89,2369
2,TXN4407425052,ACC56321,ACC92481,862.47,Withdrawal,2025-01-17 10:50:00,Failed,False,"48.8566 N, 2.3522 W",Mobile,Slice1,4,53,8039
3,TXN2214150284,ACC48650,ACC76457,1129.88,Transfer,2025-01-17 10:56:00,Success,True,"34.0522 N, -74.006 W",Mobile,Slice3,10,127,6374
4,TXN4247571145,ACC60921,ACC11419,933.24,Deposit,2025-01-17 10:25:00,Success,True,"55.7558 N, 37.6173 W",Mobile,Slice3,20,191,8375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,TXN7395336359,ACC79886,ACC14903,1340.76,Transfer,2025-01-17 10:49:00,Success,False,"35.6895 N, -118.2437 W",Mobile,Slice2,19,224,9766
996,TXN2215717837,ACC95972,ACC50750,483.36,Withdrawal,2025-01-17 11:00:00,Failed,True,"55.7558 N, 37.6173 W",Mobile,Slice2,12,56,1009
997,TXN1676848215,ACC95938,ACC18507,199.81,Withdrawal,2025-01-17 10:54:00,Success,False,"34.0522 N, 139.6917 W",Desktop,Slice1,14,151,9301
998,TXN2479413280,ACC76523,ACC95234,1341.86,Transfer,2025-01-17 10:59:00,Success,True,"51.5074 N, 139.6917 W",Mobile,Slice3,8,95,4038
999,TXN3992032184,ACC16789,ACC21980,495.36,Transfer,2025-01-17 10:02:00,Failed,False,"55.7558 N, -74.006 W",Mobile,Slice2,5,155,9888

In [31]:
# STEP 3: Changing the data present in a particular columns
b['Device Used'].unique()

array(['Desktop', 'Mobile'], dtype=object)

In [32]:
data={'Desktop':'Desk', 'Mobile':'Mob'}
b['Device Used'] = b['Device Used'].map(data)
b['Device Used'].unique()
b

,Transac_id,Sender Account ID,Receiver Account ID,Transaction Amount,Transaction Type,Timestamp,Transaction Status,Fraud Flag,Geolocation (Latitude/Longitude),Device Used,Network Slice ID,Latency (ms),Slice Bandwidth (Mbps),PIN Code
0,TXN9520068950,ACC14994,ACC16656,495.90,Deposit,2025-01-17 10:14:00,Failed,True,"34.0522 N, -74.006 W",Desk,Slice3,10,179,3075
1,TXN9412011085,ACC58958,ACC32826,529.62,Withdrawal,2025-01-17 10:51:00,Success,False,"35.6895 N, -118.2437 W",Mob,Slice2,11,89,2369
2,TXN4407425052,ACC56321,ACC92481,862.47,Withdrawal,2025-01-17 10:50:00,Failed,False,"48.8566 N, 2.3522 W",Mob,Slice1,4,53,8039
3,TXN2214150284,ACC48650,ACC76457,1129.88,Transfer,2025-01-17 10:56:00,Success,True,"34.0522 N, -74.006 W",Mob,Slice3,10,127,6374
4,TXN4247571145,ACC60921,ACC11419,933.24,Deposit,2025-01-17 10:25:00,Success,True,"55.7558 N, 37.6173 W",Mob,Slice3,20,191,8375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,TXN7395336359,ACC79886,ACC14903,1340.76,Transfer,2025-01-17 10:49:00,Success,False,"35.6895 N, -118.2437 W",Mob,Slice2,19,224,9766
996,TXN2215717837,ACC95972,ACC50750,483.36,Withdrawal,2025-01-17 11:00:00,Failed,True,"55.7558 N, 37.6173 W",Mob,Slice2,12,56,1009
997,TXN1676848215,ACC95938,ACC18507,199.81,Withdrawal,2025-01-17 10:54:00,Success,False,"34.0522 N, 139.6917 W",Desk,Slice1,14,151,9301
998,TXN2479413280,ACC76523,ACC95234,1341.86,Transfer,2025-01-17 10:59:00,Success,True,"51.5074 N, 139.6917 W",Mob,Slice3,8,95,4038
999,TXN3992032184,ACC16789,ACC21980,495.36,Transfer,2025-01-17 10:02:00,Failed,False,"55.7558 N, -74.006 W",Mob,Slice2,5,155,9888

In [35]:
# STEP 4: Remove unwanted data present in a column

b['Network Slice ID'] = b['Network Slice ID'].str.strip('Slice')
b

,Transac_id,Sender Account ID,Receiver Account ID,Transaction Amount,Transaction Type,Timestamp,Transaction Status,Fraud Flag,Geolocation (Latitude/Longitude),Device Used,Network Slice ID,Latency (ms),Slice Bandwidth (Mbps),PIN Code
0,TXN9520068950,ACC14994,ACC16656,495.90,Deposit,2025-01-17 10:14:00,Failed,True,"34.0522 N, -74.006 W",Desk,3,10,179,3075
1,TXN9412011085,ACC58958,ACC32826,529.62,Withdrawal,2025-01-17 10:51:00,Success,False,"35.6895 N, -118.2437 W",Mob,2,11,89,2369
2,TXN4407425052,ACC56321,ACC92481,862.47,Withdrawal,2025-01-17 10:50:00,Failed,False,"48.8566 N, 2.3522 W",Mob,1,4,53,8039
3,TXN2214150284,ACC48650,ACC76457,1129.88,Transfer,2025-01-17 10:56:00,Success,True,"34.0522 N, -74.006 W",Mob,3,10,127,6374
4,TXN4247571145,ACC60921,ACC11419,933.24,Deposit,2025-01-17 10:25:00,Success,True,"55.7558 N, 37.6173 W",Mob,3,20,191,8375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,TXN7395336359,ACC79886,ACC14903,1340.76,Transfer,2025-01-17 10:49:00,Success,False,"35.6895 N, -118.2437 W",Mob,2,19,224,9766
996,TXN2215717837,ACC95972,ACC50750,483.36,Withdrawal,2025-01-17 11:00:00,Failed,True,"55.7558 N, 37.6173 W",Mob,2,12,56,1009
997,TXN1676848215,ACC95938,ACC18507,199.81,Withdrawal,2025-01-17 10:54:00,Success,False,"34.0522 N, 139.6917 W",Desk,1,14,151,9301
998,TXN2479413280,ACC76523,ACC95234,1341.86,Transfer,2025-01-17 10:59:00,Success,True,"51.5074 N, 139.6917 W",Mob,3,8,95,4038
999,TXN3992032184,ACC16789,ACC21980,495.36,Transfer,2025-01-17 10:02:00,Failed,False,"55.7558 N, -74.006 W",Mob,2,5,155,9888

In [40]:
# STEP 5: Applying inbuilt functions on particular column
b['Device Used'] = b['Device Used'].str.upper()
b['Device Used'].unique()

array(['DESK', 'MOB'], dtype=object)

In [41]:
b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Transac_id                        1000 non-null   object
 1   Sender Account ID                 1000 non-null   object
 2   Receiver Account ID               1000 non-null   object
 3   Transaction Amount                1000 non-null   float64
 4   Transaction Type                  1000 non-null   object
 5   Timestamp                         1000 non-null   object
 6   Transaction Status                1000 non-null   object
 7   Fraud Flag                        1000 non-null   bool
 8   Geolocation (Latitude/Longitude)  1000 non-null   object
 9   Device Used                       1000 non-null   object
 10  Network Slice ID                  1000 non-null   object
 11  Latency (ms)                      1000 non-null   int64
 12  Slice Bandwidth (Mbps)            1000 non-null   int64
 13  PIN Code                          1000 non-null   int64
dtypes: bool(1), float64(1), int64(3), object(9)
memory usage: 102.7+ KB

In [45]:
b['Device Used'] = b['Device Used'].str.lower()
b['Device Used'].unique()

array(['desk', 'mob'], dtype=object)

In [47]:
# STEP 6 : How to handle the missing values

c = b.dropna( how = 'all')
c

,Transac_id,Sender Account ID,Receiver Account ID,Transaction Amount,Transaction Type,Timestamp,Transaction Status,Fraud Flag,Geolocation (Latitude/Longitude),Device Used,Network Slice ID,Latency (ms),Slice Bandwidth (Mbps),PIN Code
0,TXN9520068950,ACC14994,ACC16656,495.90,Deposit,2025-01-17 10:14:00,Failed,True,"34.0522 N, -74.006 W",desk,3,10,179,3075
1,TXN9412011085,ACC58958,ACC32826,529.62,Withdrawal,2025-01-17 10:51:00,Success,False,"35.6895 N, -118.2437 W",mob,2,11,89,2369
2,TXN4407425052,ACC56321,ACC92481,862.47,Withdrawal,2025-01-17 10:50:00,Failed,False,"48.8566 N, 2.3522 W",mob,1,4,53,8039
3,TXN2214150284,ACC48650,ACC76457,1129.88,Transfer,2025-01-17 10:56:00,Success,True,"34.0522 N, -74.006 W",mob,3,10,127,6374
4,TXN4247571145,ACC60921,ACC11419,933.24,Deposit,2025-01-17 10:25:00,Success,True,"55.7558 N, 37.6173 W",mob,3,20,191,8375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,TXN7395336359,ACC79886,ACC14903,1340.76,Transfer,2025-01-17 10:49:00,Success,False,"35.6895 N, -118.2437 W",mob,2,19,224,9766
996,TXN2215717837,ACC95972,ACC50750,483.36,Withdrawal,2025-01-17 11:00:00,Failed,True,"55.7558 N, 37.6173 W",mob,2,12,56,1009
997,TXN1676848215,ACC95938,ACC18507,199.81,Withdrawal,2025-01-17 10:54:00,Success,False,"34.0522 N, 139.6917 W",desk,1,14,151,9301
998,TXN2479413280,ACC76523,ACC95234,1341.86,Transfer,2025-01-17 10:59:00,Success,True,"51.5074 N, 139.6917 W",mob,3,8,95,4038
999,TXN3992032184,ACC16789,ACC21980,495.36,Transfer,2025-01-17 10:02:00,Failed,False,"55.7558 N, -74.006 W",mob,2,5,155,9888

In [48]:
# 6.1 Drop only if atleast one NaN exists in a row
c = b.dropna( how = 'any')  # If any one of the values in a row is NaN it will be dropped
c

,Transac_id,Sender Account ID,Receiver Account ID,Transaction Amount,Transaction Type,Timestamp,Transaction Status,Fraud Flag,Geolocation (Latitude/Longitude),Device Used,Network Slice ID,Latency (ms),Slice Bandwidth (Mbps),PIN Code
0,TXN9520068950,ACC14994,ACC16656,495.90,Deposit,2025-01-17 10:14:00,Failed,True,"34.0522 N, -74.006 W",desk,3,10,179,3075
1,TXN9412011085,ACC58958,ACC32826,529.62,Withdrawal,2025-01-17 10:51:00,Success,False,"35.6895 N, -118.2437 W",mob,2,11,89,2369
2,TXN4407425052,ACC56321,ACC92481,862.47,Withdrawal,2025-01-17 10:50:00,Failed,False,"48.8566 N, 2.3522 W",mob,1,4,53,8039
3,TXN2214150284,ACC48650,ACC76457,1129.88,Transfer,2025-01-17 10:56:00,Success,True,"34.0522 N, -74.006 W",mob,3,10,127,6374
4,TXN4247571145,ACC60921,ACC11419,933.24,Deposit,2025-01-17 10:25:00,Success,True,"55.7558 N, 37.6173 W",mob,3,20,191,8375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,TXN7395336359,ACC79886,ACC14903,1340.76,Transfer,2025-01-17 10:49:00,Success,False,"35.6895 N, -118.2437 W",mob,2,19,224,9766
996,TXN2215717837,ACC95972,ACC50750,483.36,Withdrawal,2025-01-17 11:00:00,Failed,True,"55.7558 N, 37.6173 W",mob,2,12,56,1009
997,TXN1676848215,ACC95938,ACC18507,199.81,Withdrawal,2025-01-17 10:54:00,Success,False,"34.0522 N, 139.6917 W",desk,1,14,151,9301
998,TXN2479413280,ACC76523,ACC95234,1341.86,Transfer,2025-01-17 10:59:00,Success,True,"51.5074 N, 139.6917 W",mob,3,8,95,4038
999,TXN3992032184,ACC16789,ACC21980,495.36,Transfer,2025-01-17 10:02:00,Failed,False,"55.7558 N, -74.006 W",mob,2,5,155,9888

In [50]:
# 6.2) Filling NaN values with zero, mean or median

b.fillna(0)
b

,Transac_id,Sender Account ID,Receiver Account ID,Transaction Amount,Transaction Type,Timestamp,Transaction Status,Fraud Flag,Geolocation (Latitude/Longitude),Device Used,Network Slice ID,Latency (ms),Slice Bandwidth (Mbps),PIN Code
0,TXN9520068950,ACC14994,ACC16656,495.90,Deposit,2025-01-17 10:14:00,Failed,True,"34.0522 N, -74.006 W",desk,3,10,179,3075
1,TXN9412011085,ACC58958,ACC32826,529.62,Withdrawal,2025-01-17 10:51:00,Success,False,"35.6895 N, -118.2437 W",mob,2,11,89,2369
2,TXN4407425052,ACC56321,ACC92481,862.47,Withdrawal,2025-01-17 10:50:00,Failed,False,"48.8566 N, 2.3522 W",mob,1,4,53,8039
3,TXN2214150284,ACC48650,ACC76457,1129.88,Transfer,2025-01-17 10:56:00,Success,True,"34.0522 N, -74.006 W",mob,3,10,127,6374
4,TXN4247571145,ACC60921,ACC11419,933.24,Deposit,2025-01-17 10:25:00,Success,True,"55.7558 N, 37.6173 W",mob,3,20,191,8375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,TXN7395336359,ACC79886,ACC14903,1340.76,Transfer,2025-01-17 10:49:00,Success,False,"35.6895 N, -118.2437 W",mob,2,19,224,9766
996,TXN2215717837,ACC95972,ACC50750,483.36,Withdrawal,2025-01-17 11:00:00,Failed,True,"55.7558 N, 37.6173 W",mob,2,12,56,1009
997,TXN1676848215,ACC95938,ACC18507,199.81,Withdrawal,2025-01-17 10:54:00,Success,False,"34.0522 N, 139.6917 W",desk,1,14,151,9301
998,TXN2479413280,ACC76523,ACC95234,1341.86,Transfer,2025-01-17 10:59:00,Success,True,"51.5074 N, 139.6917 W",mob,3,8,95,4038
999,TXN3992032184,ACC16789,ACC21980,495.36,Transfer,2025-01-17 10:02:00,Failed,False,"55.7558 N, -74.006 W",mob,2,5,155,9888

In [52]:
e = b['Transaction Amount'].mean()
print(e)

771.16529

In [53]:
b['Transaction Amount'] = b['Transaction Amount'].fillna(e)
b

,Transac_id,Sender Account ID,Receiver Account ID,Transaction Amount,Transaction Type,Timestamp,Transaction Status,Fraud Flag,Geolocation (Latitude/Longitude),Device Used,Network Slice ID,Latency (ms),Slice Bandwidth (Mbps),PIN Code
0,TXN9520068950,ACC14994,ACC16656,495.90,Deposit,2025-01-17 10:14:00,Failed,True,"34.0522 N, -74.006 W",desk,3,10,179,3075
1,TXN9412011085,ACC58958,ACC32826,529.62,Withdrawal,2025-01-17 10:51:00,Success,False,"35.6895 N, -118.2437 W",mob,2,11,89,2369
2,TXN4407425052,ACC56321,ACC92481,862.47,Withdrawal,2025-01-17 10:50:00,Failed,False,"48.8566 N, 2.3522 W",mob,1,4,53,8039
3,TXN2214150284,ACC48650,ACC76457,1129.88,Transfer,2025-01-17 10:56:00,Success,True,"34.0522 N, -74.006 W",mob,3,10,127,6374
4,TXN4247571145,ACC60921,ACC11419,933.24,Deposit,2025-01-17 10:25:00,Success,True,"55.7558 N, 37.6173 W",mob,3,20,191,8375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,TXN7395336359,ACC79886,ACC14903,1340.76,Transfer,2025-01-17 10:49:00,Success,False,"35.6895 N, -118.2437 W",mob,2,19,224,9766
996,TXN2215717837,ACC95972,ACC50750,483.36,Withdrawal,2025-01-17 11:00:00,Failed,True,"55.7558 N, 37.6173 W",mob,2,12,56,1009
997,TXN1676848215,ACC95938,ACC18507,199.81,Withdrawal,2025-01-17 10:54:00,Success,False,"34.0522 N, 139.6917 W",desk,1,14,151,9301
998,TXN2479413280,ACC76523,ACC95234,1341.86,Transfer,2025-01-17 10:59:00,Success,True,"51.5074 N, 139.6917 W",mob,3,8,95,4038
999,TXN3992032184,ACC16789,ACC21980,495.36,Transfer,2025-01-17 10:02:00,Failed,False,"55.7558 N, -74.006 W",mob,2,5,155,9888

In [54]:
d = b['Transaction Amount'].median()

d

761.655

In [55]:
b['Transaction Amount'] = b['Transaction Amount'].fillna(d)

b

,Transac_id,Sender Account ID,Receiver Account ID,Transaction Amount,Transaction Type,Timestamp,Transaction Status,Fraud Flag,Geolocation (Latitude/Longitude),Device Used,Network Slice ID,Latency (ms),Slice Bandwidth (Mbps),PIN Code
0,TXN9520068950,ACC14994,ACC16656,495.90,Deposit,2025-01-17 10:14:00,Failed,True,"34.0522 N, -74.006 W",desk,3,10,179,3075
1,TXN9412011085,ACC58958,ACC32826,529.62,Withdrawal,2025-01-17 10:51:00,Success,False,"35.6895 N, -118.2437 W",mob,2,11,89,2369
2,TXN4407425052,ACC56321,ACC92481,862.47,Withdrawal,2025-01-17 10:50:00,Failed,False,"48.8566 N, 2.3522 W",mob,1,4,53,8039
3,TXN2214150284,ACC48650,ACC76457,1129.88,Transfer,2025-01-17 10:56:00,Success,True,"34.0522 N, -74.006 W",mob,3,10,127,6374
4,TXN4247571145,ACC60921,ACC11419,933.24,Deposit,2025-01-17 10:25:00,Success,True,"55.7558 N, 37.6173 W",mob,3,20,191,8375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,TXN7395336359,ACC79886,ACC14903,1340.76,Transfer,2025-01-17 10:49:00,Success,False,"35.6895 N, -118.2437 W",mob,2,19,224,9766
996,TXN2215717837,ACC95972,ACC50750,483.36,Withdrawal,2025-01-17 11:00:00,Failed,True,"55.7558 N, 37.6173 W",mob,2,12,56,1009
997,TXN1676848215,ACC95938,ACC18507,199.81,Withdrawal,2025-01-17 10:54:00,Success,False,"34.0522 N, 139.6917 W",desk,1,14,151,9301
998,TXN2479413280,ACC76523,ACC95234,1341.86,Transfer,2025-01-17 10:59:00,Success,True,"51.5074 N, 139.6917 W",mob,3,8,95,4038
999,TXN3992032184,ACC16789,ACC21980,495.36,Transfer,2025-01-17 10:02:00,Failed,False,"55.7558 N, -74.006 W",mob,2,5,155,9888

In [56]:
b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Transac_id                        1000 non-null   object
 1   Sender Account ID                 1000 non-null   object
 2   Receiver Account ID               1000 non-null   object
 3   Transaction Amount                1000 non-null   float64
 4   Transaction Type                  1000 non-null   object
 5   Timestamp                         1000 non-null   object
 6   Transaction Status                1000 non-null   object
 7   Fraud Flag                        1000 non-null   bool
 8   Geolocation (Latitude/Longitude)  1000 non-null   object
 9   Device Used                       1000 non-null   object
 10  Network Slice ID                  1000 non-null   object
 11  Latency (ms)                      1000 non-null   int64
 12  Slice Bandwidth (Mbps)            1000 non-null   int64
 13  PIN Code                          1000 non-null   int64
dtypes: bool(1), float64(1), int64(3), object(9)
memory usage: 102.7+ KB

In [58]:
# STEP 7 : Changing the datatype of a column

b['Network Slice ID'] = b['Network Slice ID'].astype(int)
b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Transac_id                        1000 non-null   object
 1   Sender Account ID                 1000 non-null   object
 2   Receiver Account ID               1000 non-null   object
 3   Transaction Amount                1000 non-null   float64
 4   Transaction Type                  1000 non-null   object
 5   Timestamp                         1000 non-null   object
 6   Transaction Status                1000 non-null   object
 7   Fraud Flag                        1000 non-null   bool
 8   Geolocation (Latitude/Longitude)  1000 non-null   object
 9   Device Used                       1000 non-null   object
 10  Network Slice ID                  1000 non-null   int64
 11  Latency (ms)                      1000 non-null   int64
 12  Slice Bandwidth (Mbps)            1000 non-null   int64
 13  PIN Code                          1000 non-null   int64
dtypes: bool(1), float64(1), int64(4), object(8)
memory usage: 102.7+ KB

In [59]:
# STEP 8: Rearranging the order of columns

b.head()

,Transac_id,Sender Account ID,Receiver Account ID,Transaction Amount,Transaction Type,Timestamp,Transaction Status,Fraud Flag,Geolocation (Latitude/Longitude),Device Used,Network Slice ID,Latency (ms),Slice Bandwidth (Mbps),PIN Code
0,TXN9520068950,ACC14994,ACC16656,495.90,Deposit,2025-01-17 10:14:00,Failed,True,"34.0522 N, -74.006 W",desk,3,10,179,3075
1,TXN9412011085,ACC58958,ACC32826,529.62,Withdrawal,2025-01-17 10:51:00,Success,False,"35.6895 N, -118.2437 W",mob,2,11,89,2369
2,TXN4407425052,ACC56321,ACC92481,862.47,Withdrawal,2025-01-17 10:50:00,Failed,False,"48.8566 N, 2.3522 W",mob,1,4,53,8039
3,TXN2214150284,ACC48650,ACC76457,1129.88,Transfer,2025-01-17 10:56:00,Success,True,"34.0522 N, -74.006 W",mob,3,10,127,6374
4,TXN4247571145,ACC60921,ACC11419,933.24,Deposit,2025-01-17 10:25:00,Success,True,"55.7558 N, 37.6173 W",mob,3,20,191,8375

In [65]:
new_order = [1,3,4,2,0]

b = b[b.columns[new_order]]

b.head()

,Transaction Type,Transaction Amount,Receiver Account ID,Transac_id,Sender Account ID
0,Deposit,495.90,ACC16656,TXN9520068950,ACC14994
1,Withdrawal,529.62,ACC32826,TXN9412011085,ACC58958
2,Withdrawal,862.47,ACC92481,TXN4407425052,ACC56321
3,Transfer,1129.88,ACC76457,TXN2214150284,ACC48650
4,Deposit,933.24,ACC11419,TXN4247571145,ACC60921

In [66]:
# STEP 9 : Changing the data present in a particular column

b['Transaction Type'] = b['Transaction Type'].str.replace('Deposit','Deposits')

b

,Transaction Type,Transaction Amount,Receiver Account ID,Transac_id,Sender Account ID
0,Deposits,495.90,ACC16656,TXN9520068950,ACC14994
1,Withdrawal,529.62,ACC32826,TXN9412011085,ACC58958
2,Withdrawal,862.47,ACC92481,TXN4407425052,ACC56321
3,Transfer,1129.88,ACC76457,TXN2214150284,ACC48650
4,Deposits,933.24,ACC11419,TXN4247571145,ACC60921
...,...,...,...,...,...
995,Transfer,1340.76,ACC14903,TXN7395336359,ACC79886
996,Withdrawal,483.36,ACC50750,TXN2215717837,ACC95972
997,Withdrawal,199.81,ACC18507,TXN1676848215,ACC95938
998,Transfer,1341.86,ACC95234,TXN2479413280,ACC76523
999,Transfer,495.36,ACC21980,TXN3992032184,ACC16789

In [69]:
# STEP 10: Dropping unwanted column
del b['Transaction Type']
b

     Transaction Amount Receiver Account ID     Transac_id Sender Account ID
0                495.90            ACC16656  TXN9520068950          ACC14994
1                529.62            ACC32826  TXN9412011085          ACC58958
2                862.47            ACC92481  TXN4407425052          ACC56321
3               1129.88            ACC76457  TXN2214150284          ACC48650
4                933.24            ACC11419  TXN4247571145          ACC60921
..                  ...                 ...            ...               ...
995             1340.76            ACC14903  TXN7395336359          ACC79886
996              483.36            ACC50750  TXN2215717837          ACC95972
997              199.81            ACC18507  TXN1676848215          ACC95938
998             1341.86            ACC95234  TXN2479413280          ACC76523
999              495.36            ACC21980  TXN3992032184          ACC16789

[1000 rows x 4 columns]

In [71]:
f = b.drop(0, axis = 0)

f  # It will remove the mentioned index positions (row)

     Transaction Amount Receiver Account ID     Transac_id Sender Account ID
1                529.62            ACC32826  TXN9412011085          ACC58958
2                862.47            ACC92481  TXN4407425052          ACC56321
3               1129.88            ACC76457  TXN2214150284          ACC48650
4                933.24            ACC11419  TXN4247571145          ACC60921
5                449.56            ACC76710  TXN2515439857          ACC18381
..                  ...                 ...            ...               ...
995             1340.76            ACC14903  TXN7395336359          ACC79886
996              483.36            ACC50750  TXN2215717837          ACC95972
997              199.81            ACC18507  TXN1676848215          ACC95938
998             1341.86            ACC95234  TXN2479413280          ACC76523
999              495.36            ACC21980  TXN3992032184          ACC16789

[999 rows x 4 columns]

In [73]:
g = b.drop('Transac_id', axis = 1)

g  # It will remove the mentioned column

     Transaction Amount Receiver Account ID Sender Account ID
0                495.90            ACC16656          ACC14994
1                529.62            ACC32826          ACC58958
2                862.47            ACC92481          ACC56321
3               1129.88            ACC76457          ACC48650
4                933.24            ACC11419          ACC60921
..                  ...                 ...               ...
995             1340.76            ACC14903          ACC79886
996              483.36            ACC50750          ACC95972
997              199.81            ACC18507          ACC95938
998             1341.86            ACC95234          ACC76523
999              495.36            ACC21980          ACC16789

[1000 rows x 3 columns]

In [79]:
# STEP 11 : Dropping unwanted rows
b.drop('Receiver Account ID', axis=1, inplace = True)
b.head()

   Transaction Amount     Transac_id
0              495.90  TXN9520068950
1              529.62  TXN9412011085
2              862.47  TXN4407425052
3             1129.88  TXN2214150284
4              933.24  TXN4247571145

In [83]:
b.drop('Transac_id', axis=1, inplace = True)
b

     Transaction Amount
0                495.90
1                529.62
2                862.47
3               1129.88
4                933.24
..                  ...
995             1340.76
996              483.36
997              199.81
998             1341.86
999              495.36

[1000 rows x 1 columns]

In [84]:
# STEP 12 : Resetting the index values
b.reset_index(inplace=True)
b

     index  Transaction Amount
0        0              495.90
1        1              529.62
2        2              862.47
3        3             1129.88
4        4              933.24
..     ...                 ...
995    995             1340.76
996    996              483.36
997    997              199.81
998    998             1341.86
999    999              495.36

[1000 rows x 2 columns]

In [85]:
# STEP 13: Setting the column name to index positions slot
b.set_index('index', inplace=True)
b

       Transaction Amount
index
0                  495.90
1                  529.62
2                  862.47
3                 1129.88
4                  933.24
...                   ...
995               1340.76
996                483.36
997                199.81
998               1341.86
999                495.36

[1000 rows x 1 columns]