In [2]:
#PANDAS ---> Why : it is python library which used for data cleaning is called as pandas librarry

#DATA STRUCTURES IN PANDAS
#2 types
#1 ) series ---> 1D array
#2 ) Data frame ---> 2D array

In [3]:
import numpy as np
s=np.array(['hi','hello','bye'])
print(s)

['hi' 'hello' 'bye']

In [4]:
#diffrence between array and series   --->VERY IMP
#1) array belongs to numpy where as series belongs to pandas
#2)  string is treted as string itself in numpy where has in pandas it is treated as object in pandas
#3) in numpy only the array data will be displayed where as in pandas data ,index values and datatype will be displayed

In [5]:
#instalation cmd of pandas ---> pip install pandas
#import statement of panads --> import pandas as pd
import pandas as pd

In [6]:
#how to create a series
data=[10,20,30,40,50]
s=pd.Series(data)
s  # data,index value and datatype is displayed

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [7]:
#what will happen if string data is taken
data=[10,20,'hello',40,'goodbye']
s=pd.Series(data)
s
#if even a single string data is there than overal datatype will be object

0         10
1         20
2      hello
3         40
4    goodbye
dtype: object

In [8]:
#can we take other collection data types  for serries
#tuple
data=(10,20,'hello',40,'goodbye')
s=pd.Series(data)
s

0         10
1         20
2      hello
3         40
4    goodbye
dtype: object

In [9]:
#set
#data={10,20,'hello',40,'goodbye'}
#s=pd.Series(data)
#s   # set is unorederd data type

In [10]:
#dict
data={'a':10,'b':20}
s=pd.Series(data)
s # index values are replaced by key of dictionary

a    10
b    20
dtype: int64

In [11]:
#how to create dataframe
data=['yash','dharshan','sadhu maharaj','uppendra','rishab setty','ganesh']
s=pd.DataFrame(data)
s  # in this there is no strutral diffrence between series and dataframe

               0
0           yash
1       dharshan
2  sadhu maharaj
3       uppendra
4   rishab setty
5         ganesh

In [12]:
data=[[1,'yash'],[2,'dharshan'],[3,'sadhu maharaj'],[4,'uppendra'],[5,'rishab setty'],[6,'ganesh']]
s=pd.DataFrame(data)
s
#in this example  we can create multiple record[dimentions] for

   0              1
0  1           yash
1  2       dharshan
2  3  sadhu maharaj
3  4       uppendra
4  5   rishab setty
5  6         ganesh

In [13]:
#how to change the column name in dataframe
data=[[1,'yash'],[2,'dharshan'],[3,'sadhu maharaj'],[4,'uppendra'],[5,'rishab setty'],[6,'ganesh']]
s=pd.DataFrame(data, columns=['ranking','actors'])
s

   ranking         actors
0        1           yash
1        2       dharshan
2        3  sadhu maharaj
3        4       uppendra
4        5   rishab setty
5        6         ganesh

In [14]:
data=[[1,'yash'],[2,'dharshan'],[3,'sadhu maharaj'],[4,'uppendra'],[5,'rishab setty'],[6,'ganesh']]
s=pd.DataFrame(data, columns=['ranking','actors'],index = [1,2,3,4,5,6])  #chane index value
s

   ranking         actors
1        1           yash
2        2       dharshan
3        3  sadhu maharaj
4        4       uppendra
5        5   rishab setty
6        6         ganesh

In [15]:
#how to applay design column names without Dataframe syntax?
data={'ranking': [1,2,3,4,5,6],'actors':['yash','dharshan','sadhu maharaj','uppendra','rishab setty','ganesh']}
s=pd.DataFrame(data)
s

   ranking         actors
0        1           yash
1        2       dharshan
2        3  sadhu maharaj
3        4       uppendra
4        5   rishab setty
5        6         ganesh

In [16]:
#reading csv file --->
# 1) var=pd.read_csv('filename.csv /loc)
#2) var=pd.read_table('filename.txt /loc)
#3)var=pd.read_excel

In [17]:
s=pd.read_csv('https://raw.githubusercontent.com/Taj1920/Data-Analysis-Datasets/main/Datasets-Practice/titanic.csv')
s

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [18]:
#in built functions of dataframe
#1) head()
#syntax : var.head(n) where n belongs to number of rows
s.head() #if dont mention the value for n top 5 records will be displayed

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [19]:
s.head(20)

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
5,1,"Anderson, Mr. Harry",male,48.0000,0,0,19952,26.5500,E12,S,1
6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0000,1,0,13502,77.9583,D7,S,1
7,1,"Andrews, Mr. Thomas Jr",male,39.0000,0,0,112050,0.0000,A36,S,0
8,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0000,2,0,11769,51.4792,C101,S,1
9,1,"Artagaveytia, Mr. Ramon",male,71.0000,0,0,PC 17609,49.5042,NaN,C,0
10,1,"Astor, Col. John Jacob",male,47.0000,1,0,PC 17757,227.5250,C62 C64,C,0
11,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.0000,1,0,PC 17757,227.5250,C62 C64,C,1
12,1,"Aubart, Mme. Leontine Pauline",female,24.0000,0,0,PC 17477,69.3000,B35,C,1
13,1,"Barber, Miss. Ellen ""Nellie""",female,26.0000,0,0,19877,78.8500,NaN,S,1
14,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0000,0,0,27042,30.0000,A23,S,1
15,1,"Baumann, Mr. John D",male,NaN,0,0,PC 17318,25.9250,NaN,S,0
16,1,"Baxter, Mr. Quigg Edmond",male,24.0000,0,1,PC 17558,247.5208,B58 B60,C,0
17,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.0000,0,1,PC 17558,247.5208,B58 B60,C,1
18,1,"Bazzani, Miss. Albina",female,32.0000,0,0,11813,76.2917,D15,C,1
19,1,"Beattie, Mr. Thomson",male,36.0000,0,0,13050,75.2417,C6,C,0

In [20]:
#in built functions of dataframe
#2) tail()
#syntax : var.tail(n) where n belongs to number of rows
s.tail() #if dont mention the value for n bottom 5 records will be displayed

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
1304,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.8750,NaN,S,0

In [21]:
s.tail(7)

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
1302,3,"Yousif, Mr. Wazli",male,NaN,0,0,2647,7.2250,NaN,C,0
1303,3,"Yousseff, Mr. Gerious",male,NaN,0,0,2627,14.4583,NaN,C,0
1304,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.8750,NaN,S,0

In [22]:
# 3) info : it will give  the over all information of each column present in dataset
#syntax var.info()
s.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    1309 non-null   int64
 1   name      1309 non-null   object
 2   sex       1309 non-null   object
 3   age       1046 non-null   float64
 4   sibsp     1309 non-null   int64
 5   parch     1309 non-null   int64
 6   ticket    1309 non-null   object
 7   fare      1308 non-null   float64
 8   cabin     295 non-null    object
 9   embarked  1307 non-null   object
 10  survived  1309 non-null   int64
dtypes: float64(2), int64(4), object(5)
memory usage: 112.6+ KB

In [23]:
#4) desc : it gives the overall statistical information of the dataset
s.describe()

,pclass,age,sibsp,parch,fare,survived
count,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000,1309.000000
mean,2.294882,29.881135,0.498854,0.385027,33.295479,0.381971
std,0.837836,14.413500,1.041658,0.865560,51.758668,0.486055
min,1.000000,0.166700,0.000000,0.000000,0.000000,0.000000
25%,2.000000,21.000000,0.000000,0.000000,7.895800,0.000000
50%,3.000000,28.000000,0.000000,0.000000,14.454200,0.000000
75%,3.000000,39.000000,1.000000,0.000000,31.275000,1.000000
max,3.000000,80.000000,8.000000,9.000000,512.329200,1.000000

In [24]:
# 5) shape : number of rows and columns of dataset will be displayed
#syntax : var.shape
s.shape

(1309, 11)

In [25]:
# 6) column : it will display all the existing column names of the dataset
s.columns

Index(['pclass', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket', 'fare',
       'cabin', 'embarked', 'survived'],
      dtype='object')

In [26]:
#slicing on dataframe
#syntax  : var[si:ei:updation]
s[:]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [27]:
s[:101:3]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0,0,0,24160,211.3375,B5,S,1
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0,1,2,113781,151.5500,C22 C26,S,0
6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,1
9,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C,0
12,1,"Aubart, Mme. Leontine Pauline",female,24.0,0,0,PC 17477,69.3000,B35,C,1
15,1,"Baumann, Mr. John D",male,NaN,0,0,PC 17318,25.9250,NaN,S,0
18,1,"Bazzani, Miss. Albina",female,32.0,0,0,11813,76.2917,D15,C,1
21,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,1
24,1,"Bird, Miss. Ellen",female,29.0,0,0,PC 17483,221.7792,C97,S,1
27,1,"Bishop, Mrs. Dickinson H (Helen Walton)",female,19.0,1,0,11967,91.0792,B49,C,1
30,1,"Blackwell, Mr. Stephen Weart",male,45.0,0,0,113784,35.5000,T,S,0
33,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,1
36,1,"Bowerman, Miss. Elsie Edith",female,22.0,0,1,113505,55.0000,E33,S,1
39,1,"Brandeis, Mr. Emil",male,48.0,0,0,PC 17591,50.4958,B10,C,0
42,1,"Brown, Mrs. John Murray (Caroline Lane Lamson)",female,59.0,2,0,11769,51.4792,C101,S,1
45,1,"Butt, Major. Archibald Willingham",male,45.0,0,0,113050,26.5500,B38,S,0
48,1,"Candee, Mrs. Edward (Helen Churchill Hungerford)",female,53.0,0,0,PC 17606,27.4458,NaN,C,1
51,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S,0
54,1,"Carter, Master. William Thornton II",male,11.0,1,2,113760,120.0000,B96 B98,S,1
57,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.0,1,2,113760,120.0000,B96 B98,S,1
60,1,"Cavendish, Mr. Tyrell William",male,36.0,1,0,19877,78.8500,C46,S,0
63,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.1750,E31,S,1
66,1,"Chaudanson, Miss. Victorine",female,36.0,0,0,PC 17608,262.3750,B61,C,1
69,1,"Chibnall, Mrs. (Edith Martha Bowerman)",female,NaN,0,1,113505,55.0000,E33,S,1
72,1,"Clark, Mrs. Walter Miller (Virginia McDowell)",female,26.0,1,0,13508,136.7792,C89,C,1
75,1,"Colley, Mr. Edward Pomeroy",male,47.0,0,0,5727,25.5875,E58,S,0
78,1,"Compton, Mrs. Alexander Taylor (Mary Eliza Ing...",female,64.0,0,2,PC 17756,83.1583,E45,C,1
81,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S,0
84,1,"Cumings, Mr. John Bradley",male,39.0,1,0,PC 17599,71.2833,C85,C,0
87,1,"Daniel, Mr. Robert Williams",male,27.0,0,0,113804,30.5000,NaN,S,1
90,1,"Davidson, Mrs. Thornton (Orian Hays)",female,27.0,1,2,F.C. 12750,52.0000,B71,S,1
93,1,"Dodge, Dr. Washington",male,53.0,1,1,33638,81.8583,A34,S,1
96,1,"Douglas, Mr. Walter Donald",male,50.0,1,0,PC 17761,106.4250,C86,C,0
99,1,"Duff Gordon, Lady. (Lucille Christiana Sutherl...",female,48.0,1,0,11755,39.6000,A16,C,1

In [28]:
#can we slice through any particular columns
s['age'] [:51:4]

0     29.0
4     25.0
8     53.0
12    24.0
16    24.0
20    37.0
24    29.0
28    35.0
32    30.0
36    22.0
40     NaN
44    41.0
48    53.0
Name: age, dtype: float64

In [29]:
#can we slice through multiple columns simultiniously?
s[['name','embarked','sex']] [10:41:]

                                                 name embarked     sex
10                             Astor, Col. John Jacob        C    male
11  Astor, Mrs. John Jacob (Madeleine Talmadge Force)        C  female
12                      Aubart, Mme. Leontine Pauline        C  female
13                       Barber, Miss. Ellen "Nellie"        S  female
14               Barkworth, Mr. Algernon Henry Wilson        S    male
15                                Baumann, Mr. John D        S    male
16                           Baxter, Mr. Quigg Edmond        C    male
17    Baxter, Mrs. James (Helene DeLaudeniere Chaput)        C  female
18                              Bazzani, Miss. Albina        C  female
19                               Beattie, Mr. Thomson        C    male
20                      Beckwith, Mr. Richard Leonard        S    male
21   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)        S  female
22                              Behr, Mr. Karl Howell        C    male
23                              Bidois, Miss. Rosalie        C  female
24                                  Bird, Miss. Ellen        S  female
25                                Birnbaum, Mr. Jakob        C    male
26                            Bishop, Mr. Dickinson H        C    male
27            Bishop, Mrs. Dickinson H (Helen Walton)        C  female
28                             Bissette, Miss. Amelia        S  female
29          Bjornstrom-Steffansson, Mr. Mauritz Hakan        S    male
30                       Blackwell, Mr. Stephen Weart        S    male
31                                   Blank, Mr. Henry        C    male
32                            Bonnell, Miss. Caroline        S  female
33                           Bonnell, Miss. Elizabeth        S  female
34                           Borebank, Mr. John James        S    male
35                           Bowen, Miss. Grace Scott        C  female
36                        Bowerman, Miss. Elsie Edith        S  female
37      Bradley, Mr. George ("George Arthur Brayton")        S    male
38                            Brady, Mr. John Bertram        S    male
39                                 Brandeis, Mr. Emil        C    male
40                          Brewe, Dr. Arthur Jackson        C    male

In [30]:
#LOC ---> Used to perform slicing 1st and specifies the columns
#syntax == var.loc[rowslice,'col_name']
s.loc[10:36,'name']

10                               Astor, Col. John Jacob
11    Astor, Mrs. John Jacob (Madeleine Talmadge Force)
12                        Aubart, Mme. Leontine Pauline
13                         Barber, Miss. Ellen "Nellie"
14                 Barkworth, Mr. Algernon Henry Wilson
15                                  Baumann, Mr. John D
16                             Baxter, Mr. Quigg Edmond
17      Baxter, Mrs. James (Helene DeLaudeniere Chaput)
18                                Bazzani, Miss. Albina
19                                 Beattie, Mr. Thomson
20                        Beckwith, Mr. Richard Leonard
21     Beckwith, Mrs. Richard Leonard (Sallie Monypeny)
22                                Behr, Mr. Karl Howell
23                                Bidois, Miss. Rosalie
24                                    Bird, Miss. Ellen
25                                  Birnbaum, Mr. Jakob
26                              Bishop, Mr. Dickinson H
27              Bishop, Mrs. Dickinson H (Helen Walton)
28                               Bissette, Miss. Amelia
29            Bjornstrom-Steffansson, Mr. Mauritz Hakan
30                         Blackwell, Mr. Stephen Weart
31                                     Blank, Mr. Henry
32                              Bonnell, Miss. Caroline
33                             Bonnell, Miss. Elizabeth
34                             Borebank, Mr. John James
35                             Bowen, Miss. Grace Scott
36                          Bowerman, Miss. Elsie Edith
Name: name, dtype: object

In [31]:
#usecase 2 ---> with updation
s.loc[10: 36: 5,'name']

10           Astor, Col. John Jacob
15              Baumann, Mr. John D
20    Beckwith, Mr. Richard Leonard
25              Birnbaum, Mr. Jakob
30     Blackwell, Mr. Stephen Weart
35         Bowen, Miss. Grace Scott
Name: name, dtype: object

In [32]:
#usecase 3 ---> specifically mention the

#when to do this?
#when there is no proper updation in the value
s.loc[[10,20,30,40,50],'name'] #commn updation

10                               Astor, Col. John Jacob
20                        Beckwith, Mr. Richard Leonard
30                         Blackwell, Mr. Stephen Weart
40                            Brewe, Dr. Arthur Jackson
50    Cardeza, Mrs. James Warburton Martinez (Charlo...
Name: name, dtype: object

In [33]:
s.loc[[10,27,32,44,56],'name']

10                     Astor, Col. John Jacob
27    Bishop, Mrs. Dickinson H (Helen Walton)
32                    Bonnell, Miss. Caroline
44            Burns, Miss. Elizabeth Margaret
56                 Carter, Mr. William Ernest
Name: name, dtype: object

In [34]:
#Iloc ---> it is used to slice through both rows and columns

#syntax : var.iloc[row_slice,col_slice]
#usecase1 : when both the arguments are of slicing
s.iloc[10:21:2,0:7:2]

    pclass     sex  sibsp    ticket
10       1    male      1  PC 17757
12       1  female      0  PC 17477
14       1    male      0     27042
16       1    male      0  PC 17558
18       1  female      0     11813
20       1    male      1     11751

In [35]:
#usecase1: when both argumentsare of selective type
s.iloc[[1,5,7,11,13,],[0,4,5,7]]

    pclass  sibsp  parch     fare
1        1      1      2  151.550
5        1      0      0   26.550
7        1      0      0    0.000
11       1      1      0  227.525
13       1      0      0   78.850

In [36]:
#usecase3 : when first argument is slicing and other one is selective type
s.iloc[15:27:3,[1,4,6,7]]

,name,sibsp,ticket,fare
15,"Baumann, Mr. John D",0,PC 17318,25.9250
18,"Bazzani, Miss. Albina",0,11813,76.2917
21,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",1,11751,52.5542
24,"Bird, Miss. Ellen",0,PC 17483,221.7792

In [37]:
#usecase4 : when the first argument is selective type and the other one is slicing type
s.iloc[[4,7,10,11],1:7:2]

                                                 name   age  parch
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  25.0      2
7                              Andrews, Mr. Thomas Jr  39.0      0
10                             Astor, Col. John Jacob  47.0      0
11  Astor, Mrs. John Jacob (Madeleine Talmadge Force)  18.0      0

In [38]:
#boolean filtering ---> based on the boolean values we are filtering the records
#syntax : var[condition]

#display all the female data
s[s['sex']=='female']

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0,0,0,24160,211.3375,B5,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.5500,C22 C26,S,0
6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,1
8,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,1
...,...,...,...,...,...,...,...,...,...,...,...
1286,3,"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",female,38.0,0,0,2688,7.2292,NaN,C,1
1290,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,1
1300,3,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.0,1,0,2659,14.4542,NaN,C,1
1304,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0

In [39]:
#display age of all the male

s['age'] [s['sex']=='male']

1        0.9167
3       30.0000
5       48.0000
7       39.0000
9       71.0000
         ...
1302        NaN
1303        NaN
1306    26.5000
1307    27.0000
1308    29.0000
Name: age, Length: 843, dtype: float64

In [40]:
s[(s['sex']=='female') & (s['age']>50) & (s['survived']==1)]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,1
8,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,1
33,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,1
42,1,"Brown, Mrs. John Murray (Caroline Lane Lamson)",female,59.0,2,0,11769,51.4792,C101,S,1
43,1,"Bucknell, Mrs. William Robert (Emma Eliza Ward)",female,60.0,0,0,11813,76.2917,D15,C,1
48,1,"Candee, Mrs. Edward (Helen Churchill Hungerford)",female,53.0,0,0,PC 17606,27.4458,NaN,C,1
50,1,"Cardeza, Mrs. James Warburton Martinez (Charlo...",female,58.0,0,1,PC 17755,512.3292,B51 B53 B55,C,1
61,1,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1,0,19877,78.8500,C46,S,1
78,1,"Compton, Mrs. Alexander Taylor (Mary Eliza Ing...",female,64.0,0,2,PC 17756,83.1583,E45,C,1
79,1,"Cornell, Mrs. Robert Clifford (Malvina Helen L...",female,55.0,2,0,11770,25.7000,C101,S,1
83,1,"Crosby, Mrs. Edward Gifford (Catherine Elizabe...",female,64.0,1,1,112901,26.5500,B26,S,1
95,1,"Dodge, Mrs. Washington (Ruth Vidaver)",female,54.0,1,1,33638,81.8583,A34,S,1
104,1,"Eustis, Miss. Elizabeth Mussey",female,54.0,1,0,36947,78.2667,D20,C,1
116,1,"Fortune, Mrs. Mark (Mary McDougald)",female,60.0,1,4,19950,263.0000,C23 C25 C27,S,1
139,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.0,0,1,PC 17582,153.4625,C125,S,1
155,1,"Hays, Mrs. Charles Melville (Clara Jennings Gr...",female,52.0,1,1,12749,93.5000,B69,S,1
161,1,"Hogeboom, Mrs. John C (Anna Andrews)",female,51.0,1,0,13502,77.9583,D11,S,1
186,1,"Lindstrom, Mrs. Carl Johan (Sigrid Posse)",female,55.0,0,0,112377,27.7208,NaN,C,1
188,1,"Lines, Mrs. Ernest H (Elizabeth Lindsey James)",female,51.0,0,1,PC 17592,39.4000,D28,S,1
192,1,"Lurette, Miss. Elise",female,58.0,0,0,PC 17569,146.5208,B80,C,1
233,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,1
247,1,"Rothschild, Mrs. Martin (Elizabeth L. Barrett)",female,54.0,1,0,PC 17603,59.4000,NaN,C,1
282,1,"Stephenson, Mrs. Walter Bertram (Martha Eustis)",female,52.0,1,0,36947,78.2667,D20,C,1
284,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN,1
304,1,"Warren, Mrs. Frank Manley (Anna Sophia Atkinson)",female,60.0,1,0,110813,75.2500,D37,C,1
308,1,"White, Mrs. John Stuart (Ella Holmes)",female,55.0,0,0,PC 17760,135.6333,C32,C,1
441,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S,1
449,2,"Hocking, Mrs. Elizabeth (Eliza Needs)",female,54.0,1,3,29105,23.0000,NaN,S,1
1261,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S,1

In [41]:
#how to identify the null values in the dataset

s[s['age'].isnull()]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
15,1,"Baumann, Mr. John D",male,NaN,0,0,PC 17318,25.9250,NaN,S,0
37,1,"Bradley, Mr. George (""George Arthur Brayton"")",male,NaN,0,0,111427,26.5500,NaN,S,1
40,1,"Brewe, Dr. Arthur Jackson",male,NaN,0,0,112379,39.6000,NaN,C,0
46,1,"Cairns, Mr. Alexander",male,NaN,0,0,113798,31.0000,NaN,S,0
59,1,"Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genev...",female,NaN,0,0,17770,27.7208,NaN,C,1
...,...,...,...,...,...,...,...,...,...,...,...
1293,3,"Williams, Mr. Howard Hugh ""Harry""",male,NaN,0,0,A/5 2466,8.0500,NaN,S,0
1297,3,"Wiseman, Mr. Phillippe",male,NaN,0,0,A/4. 34244,7.2500,NaN,S,0
1302,3,"Yousif, Mr. Wazli",male,NaN,0,0,2647,7.2250,NaN,C,0
1303,3,"Yousseff, Mr. Gerious",male,NaN,0,0,2627,14.4583,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0

In [42]:
s[s['age'].isna()]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
15,1,"Baumann, Mr. John D",male,NaN,0,0,PC 17318,25.9250,NaN,S,0
37,1,"Bradley, Mr. George (""George Arthur Brayton"")",male,NaN,0,0,111427,26.5500,NaN,S,1
40,1,"Brewe, Dr. Arthur Jackson",male,NaN,0,0,112379,39.6000,NaN,C,0
46,1,"Cairns, Mr. Alexander",male,NaN,0,0,113798,31.0000,NaN,S,0
59,1,"Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genev...",female,NaN,0,0,17770,27.7208,NaN,C,1
...,...,...,...,...,...,...,...,...,...,...,...
1293,3,"Williams, Mr. Howard Hugh ""Harry""",male,NaN,0,0,A/5 2466,8.0500,NaN,S,0
1297,3,"Wiseman, Mr. Phillippe",male,NaN,0,0,A/4. 34244,7.2500,NaN,S,0
1302,3,"Yousif, Mr. Wazli",male,NaN,0,0,2647,7.2250,NaN,C,0
1303,3,"Yousseff, Mr. Gerious",male,NaN,0,0,2627,14.4583,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0

In [43]:
#how to get all not null values from the dataset
s[s['age'].notnull()]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1301,3,"Youseff, Mr. Gerious",male,45.5000,0,0,2628,7.2250,NaN,C,0
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [44]:
s[s['age'].notna()]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1301,3,"Youseff, Mr. Gerious",male,45.5000,0,0,2628,7.2250,NaN,C,0
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [45]:
#DATA CLEANING---->It is used to remove unwanted /irrelevant data from datasets

#There are totally 13 cleaning steps

In [46]:
#ENCODING='latin'
encoding='latin-1'
encoding='ISO-8859-1'
b=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/amazon_fires.csv',encoding='latin-1')

In [47]:
b = pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/amazon_fires.csv', encoding='latin-1')
b

       ano       mes     estado   numero  encontro
0     1998   Janeiro       Acre  0 Fires  1/1/1998
1     1999   Janeiro       Acre  0 Fires  1/1/1999
2     2000   Janeiro       Acre  0 Fires  1/1/2000
3     2001   Janeiro       Acre  0 Fires  1/1/2001
4     2002   Janeiro       Acre  0 Fires  1/1/2002
...    ...       ...        ...      ...       ...
6449  2012  Dezembro  Tocantins      128  1/1/2012
6450  2013  Dezembro  Tocantins       85  1/1/2013
6451  2014  Dezembro  Tocantins      223  1/1/2014
6452  2015  Dezembro  Tocantins      373  1/1/2015
6453  2016  Dezembro  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

In [48]:
#DATA CLEANING

# STEP 1: Renaming the columns
# SYNTAX : var1 = {'old_col1':'new_col1',........,'old_colN':'new_colN'}
         # var.rename(columns = var1, inplace = True)

#inplace = True ---> It will permanantly change the data

In [49]:
data ={
    'ano':'Year',
    'mes':'Month',
    'estado':'State',
    'numero':'No_of_fires',
    'encontro':'Date'
}
b.rename(columns=data,inplace=True)
b

      Year     Month      State No_of_fires      Date
0     1998   Janeiro       Acre     0 Fires  1/1/1998
1     1999   Janeiro       Acre     0 Fires  1/1/1999
2     2000   Janeiro       Acre     0 Fires  1/1/2000
3     2001   Janeiro       Acre     0 Fires  1/1/2001
4     2002   Janeiro       Acre     0 Fires  1/1/2002
...    ...       ...        ...         ...       ...
6449  2012  Dezembro  Tocantins         128  1/1/2012
6450  2013  Dezembro  Tocantins          85  1/1/2013
6451  2014  Dezembro  Tocantins         223  1/1/2014
6452  2015  Dezembro  Tocantins         373  1/1/2015
6453  2016  Dezembro  Tocantins         119  1/1/2016

[6454 rows x 5 columns]

In [50]:
# STEP 2: REMOVING DUPLICATE VALUES
#SYNTAX: var.drop_duplicates(inplace=True)


c = pd.DataFrame({
    'name': ['sushanth','jaya','jaya','moni','nagaraj'],
    'roll_no' : [80,46,46,82,67],
    'marks' : [100,80,80,86,90],
    'gender' : ['M','F','F','M','M']
})
c

       name  roll_no  marks gender
0  sushanth       80    100      M
1      jaya       46     80      F
2      jaya       46     80      F
3      moni       82     86      M
4   nagaraj       67     90      M

In [51]:
c.drop_duplicates(inplace=True)
c
#if bothe the rows are having same functionalities , then it will be dropped

       name  roll_no  marks gender
0  sushanth       80    100      M
1      jaya       46     80      F
3      moni       82     86      M
4   nagaraj       67     90      M

In [52]:
# STEP 3: CHANGING THE DATA PRESENT IN A PARTICULAR COLUMN
# SYNTAX : var['col_name']= var['col_name'].map(dict)
b['Month'].unique()   #extractig unique values from a column

array(['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho',
       'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
      dtype=object)

In [53]:
data = {'Janeiro':'January', 'Fevereiro':'February', 'Março':'March', 'Abril':'April', 'Maio':'May', 'Junho':'June', 'Julho':'July',
       'Agosto':'August', 'Setembro':'September', 'Outubro':'October', 'Novembro':'November', 'Dezembro':'December'}

b['Month'] = b['Month'].map(data)
b['Month'].unique()

array(['January', 'February', 'March', 'April', 'May', 'June', 'July',
       'August', 'September', 'October', 'November', 'December'],
      dtype=object)

In [54]:
# STEP 4: REMOVE UNWANTED DATA PRESENT IN A COLUMN
#SYNTAX: var['col_name']=var['col_name'].str.strip('Unwanted data')
b['No_of_fires']=b['No_of_fires'].str.strip('Fires')
b

      Year     Month      State No_of_fires      Date
0     1998   January       Acre          0   1/1/1998
1     1999   January       Acre          0   1/1/1999
2     2000   January       Acre          0   1/1/2000
3     2001   January       Acre          0   1/1/2001
4     2002   January       Acre          0   1/1/2002
...    ...       ...        ...         ...       ...
6449  2012  December  Tocantins         128  1/1/2012
6450  2013  December  Tocantins          85  1/1/2013
6451  2014  December  Tocantins         223  1/1/2014
6452  2015  December  Tocantins         373  1/1/2015
6453  2016  December  Tocantins         119  1/1/2016

[6454 rows x 5 columns]

In [55]:
# STEP 5: Applying inbuilt functions on particular column

#Syntax: var['col_name']=var['col_name'].str.fname()

b['Month']=b['Month'].str.upper()
b['Month'].unique()

array(['JANUARY', 'FEBRUARY', 'MARCH', 'APRIL', 'MAY', 'JUNE', 'JULY',
       'AUGUST', 'SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER'],
      dtype=object)

In [56]:
b['State'].unique()

array(['Acre', 'alagoas', 'Amapa', 'Amazonas', 'Bahia', 'Ceara',
       'Distrito Federal', 'Espirito Santo', 'Goias', 'Maranhao',
       'Mato Grosso', 'Minas Gerais', 'pará', 'Paraiba', 'Pernambuco',
       'Piau', 'Rio', 'rondonia', 'Roraima', 'Santa Catarina',
       'Sao Paulo', 'Sergipe', 'Tocantins'], dtype=object)

In [57]:
b['State']=b['State'].str.lower()
b['State'].unique()

array(['acre', 'alagoas', 'amapa', 'amazonas', 'bahia', 'ceara',
       'distrito federal', 'espirito santo', 'goias', 'maranhao',
       'mato grosso', 'minas gerais', 'pará', 'paraiba', 'pernambuco',
       'piau', 'rio', 'rondonia', 'roraima', 'santa catarina',
       'sao paulo', 'sergipe', 'tocantins'], dtype=object)